PATH=~/bin:$PATH:.

# Prompt Foo
GREEN='\[\e[0;32m\]'
BGREEN='\[\e[1;32m\]'
BLUE='\[\e[1;34m\]'
WHITE='\[\e[1;37m\]'
RED='\[\e[0;31m\]'
DEFAULT='\[\e[0m\]'
RET_SUCC="\[\033[32;1m\]v";
RET_FAIL="\[\033[31;1m\]x";
PROMPT_COMMAND='RET=$?; if [[ $RET -eq 0 ]]; then export PS1="${RET_SUCC} ${_PS1}"; else export PS1="${RET_FAIL} ${_PS1}"; fi'

_PS1="\u (\t) $BLUE\w $BGREEN\$ $DEFAULT"

# Colorful ls
alias ls='ls -FG'
export LSCOLORS="eafxcxdxbxegedabagacad"

export EDITOR='vim'
alias edit='$EDITOR'
