" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Show encoding in Statusline
if has("statusline")
 set statusline=%<%f\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %-14.(%l,%c%V%)\ %P
endif

colorscheme diablo3
set hidden
set ofu=syntaxcomplete#Complete

map <silent> <C-a> :call BufferList()<CR>

let g:BufferListWidth = 25
let g:BufferListMaxWidth = 50
hi BufferSelected term=reverse ctermfg=white ctermbg=red cterm=bold
hi BufferNormal term=NONE ctermfg=black ctermbg=darkcyan cterm=NONE

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac


set autoindent smartindent		" always set autoindenting on
set autowrite
set tabstop=4
set shiftwidth=4
set showmatch
set guioptions-=T
set incsearch
set nocompatible
set backspace=indent,eol,start
set backup
set backupdir=~/.vim_backup
set history=50
set ruler
set showcmd
set incsearch
set autochdir
set number
set smarttab
set undolevels=1000
set complete=.,w,b,u,U,t,i,d
set wildmode=longest:full
set wildmenu
set ignorecase
set hlsearch
set wrap
set expandtab

filetype plugin on
let filetype_m='objc'

syntax on

inoremap ' ''<Left>
inoremap " ""<Left>
inoremap ( ()<Left>
" inoremap < <><Left>
inoremap { {}<Left>
inoremap [ []<Left>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Move a line of text using ALT+[jk] or Comamnd+[jk] on mac
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

if has("mac") || has("macunix")
  nmap <D-j> <M-j>
  nmap <D-k> <M-k>
  vmap <D-j> <M-j>
  vmap <D-k> <M-k>
endif

if has("gui_running")
	set columns=120
    set lines=70
	set transparency=10
	set guifont=Bitstream\ Vera\ Sans\ Mono:h14
endif
