# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="aussiegeek"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github osx zsh-syntax-highlighting macports brew)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=~/bin:/opt/local/bin:/usr/local/git/bin:/usr/local/share/python:/usr/local/bin:/bin:/usr/local/sbin:/sbin:/usr/bin:/usr/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/usr/games/bin:~/Android/adt-bundle-mac-x86_64/sdk/platforms:~/Android/adt-bundle-mac-x86_64/sdk/platform-tools:~/Android/adt-bundle-mac-x86_64/sdk/tools:/usr/texbin:/opt/arm-gcc/gcc-arm-none-eabi/bin:/Users/thomas/dmd2/osx/bin:/Applications/Doxygen.app/Contents/Resources:/opt/gbdk/bin:.

export EDITOR=vim
export LPC_DEPLOY='cp PROJECT.bin /Volumes/MBED/'
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

alias crontab="VIM_CRONTAB=true crontab"
